include $(GOROOT)/src/Make.$(GOARCH)

TARG=teratogen
GOFILES=\
	ai.go\
	area.go\
	contain.go\
	context.go\
	creature.go\
	entity.go\
	factory.go\
	globals.go\
	los.go\
	mapgen.go\
	msg.go\
	rng.go\
	rules.go\
	world.go\

include $(GOROOT)/src/Make.pkg
