include $(GOROOT)/src/Make.$(GOARCH)

TARG=teratogen
GOFILES=\
	ai.go\
	area.go\
	combat.go\
	contain.go\
	context.go\
	creature.go\
	decal.go\
	effects.go\
	factory.go\
	globals.go\
	item.go\
	los.go\
	mapgen.go\
	name.go\
	position.go\
	rules.go\

include $(GOROOT)/src/Make.pkg
