include $(GOROOT)/src/Make.$(GOARCH)

TARG=hyades/gamelib
GOFILES=\
	alg.go\
	color.go\
	console.go\
	debug.go\
	geom.go\
	graph.go\
	mem.go\
	num.go\
	rng.go\
	set.go\
	string.go\
	tiles.go\

include $(GOROOT)/src/Make.pkg
