include $(GOROOT)/src/Make.inc

TARG=teratogen/game
GOFILES=\
	ai.go\
	area.go\
	contain.go\
	context.go\
	creature.go\
	decal.go\
	effects.go\
	factory.go\
	fov.go\
	globals.go\
	heartbeat.go\
	inventory.go\
	item.go\
	mapgen.go\
	mutation.go\
	name.go\
	position.go\
	power.go\
	rules.go\
	version.go\
	weapon.go\

include $(GOROOT)/src/Make.pkg
