include $(GOROOT)/src/Make.$(GOARCH)

TARG=teratogen/teratogen
GOFILES=\
	ai.go\
	area.go\
	config.go\
	contain.go\
	creature.go\
	entity.go\
	factory.go\
	mapgen.go\
	msg.go\
	rules.go\
	world.go\

include $(GOROOT)/src/Make.pkg
